vname: 'Run Trivy scan - linux - with summary'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any vulnerabilities and adds a step summary'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: ${{ github.workspace }}
  severity:
    description: "Severity to flag on"
    required: false
    default: LOW,MEDIUM,HIGH,CRITICAL
  type:
    description: "Type of scan to run"
    required: false
    default: fs
  output_format:
    description: "Type of output file to return"
    required: false
    default: markdown

runs:
  using: composite
  steps:
    # https://trivy.dev/v0.18.3/installation/
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Run Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: scan
      run: | 
        trivy ${{ inputs.type }} \
          --scanners vuln,misconfig,secret,license \
          --format template \
          --template "@templates/${{ inputs.output_format }}.tpl" \
          --output "${{ inputs.working_dir}}-report" \
          --severity ${{ inputs.severity}} \
          ${{ inputs.working_dir}}

        #TODO: should probably change the file extension by detecting the format here... some day
        
        # Add the report to the GitHub step summary
        cat "${{ inputs.working_dir}}-report" >> $GITHUB_STEP_SUMMARY
