name: 'Run Trivy scan - linux - with summary'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any vulnerabilities and adds a step summary'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: .
  severity:
    description: "Severity to flag on"
    required: false
    default: LOW,MEDIUM,HIGH,CRITICAL
  type:
    description: "Type of scan to run"
    required: false
    default: fs

runs:
  using: composite
  steps:
    # https://trivy.dev/v0.18.3/installation/
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Run Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: scan
      run: | 
        trivy ${{ inputs.type }} ${{ inputs.debug_output }} --scanners vuln,misconfig,secret,license --format json --output "./${{ inputs.working_dir}}-${{ inputs.type }}.json" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}

    - name: Consolidate Report
      shell: bash
      run: |
        # Function to convert Trivy JSON output to Markdown
        convert_to_md() {
          local input_file=$1
          local output_file=$2
          
          echo "### Vulnerabilities Detected" > "$output_file"
          echo "" >> "$output_file"
          echo "| Package | Vulnerability ID | Severity | Description |" >> "$output_file"
          echo "|---------|-----------------|-----------|-------------|" >> "$output_file"
          
          jq -r '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | "| \(.PkgName) | \(.VulnerabilityID) | \(.Severity) | \(.Description) |"' "$input_file" >> "$output_file"
        }      
        echo "# Trivy Security Scan - ${{ inputs.type }}" >> reportssummary.md
        echo "<details>" >> reportssummary.md
        convert_to_md "${{ inputs.working_dir }}-${{ inputs.type }}.json" "${{ inputs.working_dir }}-${{ inputs.type }}-report.md"
        cat "${{ inputs.working_dir }}-${{ inputs.type }}-report.md" >> reportssummary.md
        echo "</details>" >> reportssummary.md
        cat"${{ inputs.working_dir }}-${{ inputs.type }}-report.md" >> $GITHUB_STEP_SUMMARY
