name: 'Run Trivy scan - linux - with summary'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any IaC vulnerabilities'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: .
  severity:
    description: "Severity to flag on"
    required: false
    default: HIGH,CRITICAL
  format:
    description: "Scan format"
    required: false
    default: github

runs:
  using: composite
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Run Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: scan
      run: | 
        trivy config ${{ inputs.debug_output }} --format ${{ inputs.format }} --output "./${{ inputs.working_dir}}-trivy-report.${{ inputs.format }}" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}
        trivy fs ${{ inputs.debug_output }} --format ${{ inputs.format }} --output "./${{ inputs.working_dir}}-fs-report.${{ inputs.format }}" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}
        
    - name: Consolidate Reports
      shell: bash
      if: ${{ inputs.format == 'github' }}
      run: |
        echo "# CI Code Scan Report" > reportssummary.md
        echo "## Trivy Security Scan - config" >> reportssummary.md
        cat ${{ inputs.working_dir}}-trivy-report.${{ inputs.format }} >> reportssummary.md
        echo "## Trivy Security Scan - fs" >> reportssummary.md
        cat ${{ inputs.working_dir}}-fs-report.${{ inputs.format }} >> reportssummary.md
        cat reportssummary.md >> $GITHUB_STEP_SUMMARY
