name: 'Run Trivy scan - linux - with summary'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any IaC vulnerabilities'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: .
  severity:
    description: "Severity to flag on"
    required: false
    default: HIGH,CRITICAL

runs:
  using: composite
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Run Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: scan
      run: | 
        trivy fs --scanners vuln,misconfig,secret,license --format json --output "./${{ inputs.working_dir}}-fs-report.json" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}
        trivy repo --format json --output "./${{ inputs.working_dir}}-repo-report.json" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}

    - name: Convert Trivy JSON reports to Markdown
      shell: bash
      run: |
        echo "# CI Code Scan Report" > reportssummary.md
        echo "## Trivy Security Scan - fs" >> reportssummary.md
        jq -r '
          .Results[] | 
          "### Vulnerabilities in \(.Target)\n" + 
          (
            if .Vulnerabilities then 
              (.Vulnerabilities[] | "- **\(.Severity)** \(.Title) (\(.VulnerabilityID))") 
            else 
              "*No vulnerabilities found*" 
            end
          )
        ' "./${{ inputs.working_dir}}-fs-report.json" >> reportssummary.md
        echo "## Trivy Security Scan - repo" >> reportssummary.md
        jq -r '
          .Results[] | 
          "### Vulnerabilities in \(.Target)\n" + 
          (
            if .Vulnerabilities then 
              (.Vulnerabilities[] | "- **\(.Severity)** \(.Title) (\(.VulnerabilityID))") 
            else 
              "*No vulnerabilities found*" 
            end
          )
        ' "./${{ inputs.working_dir}}-repo-report.json" >> reportssummary.md

    - name: Append Markdown summary to $GITHUB_STEP_SUMMARY
      shell: bash
      run: |
        cat reportssummary.md >> $GITHUB_STEP_SUMMARY
