name: 'Run Trivy IaC scan'
author: 'xander-rudolph'
branding:
  icon: 'git-pull-request'
  color: 'green'
description: 'Checks a directory for any IaC vulnerabilities'
inputs:
  working_dir:
    description: "Working path for scan"
    required: false
    default: .
  severity:
    description: "Severity to flag on"
    required: false
    default: HIGH,CRITICAL
  format:
    description: "Scan format"
    required: false
    default: sarif
  debug_output:
    description: "Enable debug flag (set to '-d' to enable)"
    required: false
    default: ""
  gh_pages_branch:
    description: "Branch name for github pages results (leave blank to disable)"
    required: false
    default: ""
  gh_pages_results:
    description: "Path for result files to process"
    required: false
    default: "results"

runs:
  using: composite
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Run Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: scan
      run: | 
        trivy config ${{ inputs.debug_output }} --format ${{ inputs.format }} --output "./${{ inputs.working_dir}}-trivy-report.${{ inputs.format }}" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}
        trivy fs ${{ inputs.debug_output }} --format ${{ inputs.format }} --output "./${{ inputs.working_dir}}-fs-report.${{ inputs.format }}" --severity ${{ inputs.severity}} ${{ inputs.working_dir}}

    - name: Parse Trivy scan on ${{ inputs.working_dir }}
      shell: bash
      id: parse
      continue-on-error: true
      run: | 
        errors=$(jq -r '.runs[].results[] | select(.level == "error")' "./${{ inputs.working_dir}}-trivy-report.${{ inputs.format }}")
        echo "The following errors were found:\n\t$errors"
        echo "results=$errors" >> $GITHUB_OUTPUT

    - name: Update PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Trivy scan: ⚙️\`${{ steps.scan.outcome }}\`
          <details><summary>show console out</summary>

          \`\`\`\n
          ${{ steps.scan.stdout }}
          \`\`\`

          </details>

          <details><summary>Errors</summary>

          \`\`\`\n
          ${{ steps.parse.outputs.results }}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
          
    - name: Upload Trivy scan to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.working_dir}} Trivy Results
        path: |
          ${{ inputs.working_dir}}-trivy-report.${{ inputs.format }}
          ${{ inputs.working_dir}}-fs-report.${{ inputs.format }}
          
    - name: Get Pages source
      if: ${{ inputs.gh_pages_branch != '' }}
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.gh_pages_results }}
        ref: ${{ inputs.gh_pages_branch }}

    - name: Update Pages sarif
      if: ${{ inputs.gh_pages_branch != '' }}
      shell: bash
      run: |
          cp ./${{ inputs.working_dir}}-trivy-report.${{ inputs.format }} ${{ inputs.gh_pages_results }}/${{ inputs.working_dir}}-trivy-report.${{ inputs.format }}
          cp ./${{ inputs.working_dir}}-fs-report.${{ inputs.format }} ${{ inputs.gh_pages_results }}/${{ inputs.working_dir}}-fs-report.${{ inputs.format }}
          cd ${{ inputs.gh_pages_results }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Sarifs updated"
          git push
